package com.college.platform.config;

import com.college.platform.model.AdBoost;
import com.college.platform.model.AutopilotConfig;
import com.college.platform.model.InboxMessage;
import com.college.platform.model.SocialPost;
import com.college.platform.repository.AdBoostRepository;
import com.college.platform.repository.AutopilotConfigRepository;
import com.college.platform.repository.InboxMessageRepository;
import com.college.platform.repository.SocialPostRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component
public class DataSeeder implements CommandLineRunner {

    @Autowired
    private SocialPostRepository socialPostRepository;

    @Autowired
    private AdBoostRepository adBoostRepository;

    @Autowired
    private InboxMessageRepository inboxMessageRepository;

    @Autowired
    private AutopilotConfigRepository autopilotConfigRepository;

    @Override
    public void run(String... args) throws Exception {
        // No mock data. We only use real data generated by the user or from the knowledge base.
    }
}
