package com.college.platform.dto;

import com.college.platform.model.SocialPost;
import com.college.platform.model.AutopilotConfig;
import java.util.List;

public class DashboardResponse {
    private long drafts;
    private long scheduled;
    private long published;
    private long failed;
    private long autoGenerated;
    private long activeBoosts;
    private long inboxUnread;
    private long pendingBoosts;
    private long lowAccuracyDrafts;
    private List<SocialPost> recentPosts;
    private AutopilotConfig autopilotConfig;

    // Getters and Setters
    public long getDrafts() { return drafts; }
    public void setDrafts(long drafts) { this.drafts = drafts; }

    public long getScheduled() { return scheduled; }
    public void setScheduled(long scheduled) { this.scheduled = scheduled; }

    public long getPublished() { return published; }
    public void setPublished(long published) { this.published = published; }

    public long getFailed() { return failed; }
    public void setFailed(long failed) { this.failed = failed; }

    public long getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(long autoGenerated) { this.autoGenerated = autoGenerated; }

    public long getActiveBoosts() { return activeBoosts; }
    public void setActiveBoosts(long activeBoosts) { this.activeBoosts = activeBoosts; }

    public long getInboxUnread() { return inboxUnread; }
    public void setInboxUnread(long inboxUnread) { this.inboxUnread = inboxUnread; }

    public long getPendingBoosts() { return pendingBoosts; }
    public void setPendingBoosts(long pendingBoosts) { this.pendingBoosts = pendingBoosts; }

    public long getLowAccuracyDrafts() { return lowAccuracyDrafts; }
    public void setLowAccuracyDrafts(long lowAccuracyDrafts) { this.lowAccuracyDrafts = lowAccuracyDrafts; }

    public List<SocialPost> getRecentPosts() { return recentPosts; }
    public void setRecentPosts(List<SocialPost> recentPosts) { this.recentPosts = recentPosts; }

    public AutopilotConfig getAutopilotConfig() { return autopilotConfig; }
    public void setAutopilotConfig(AutopilotConfig autopilotConfig) { this.autopilotConfig = autopilotConfig; }
}
