package com.college.platform.controller;

import com.college.platform.dto.DashboardResponse;
import com.college.platform.model.AutopilotConfig;
import com.college.platform.repository.AdBoostRepository;
import com.college.platform.repository.AutopilotConfigRepository;
import com.college.platform.repository.InboxMessageRepository;
import com.college.platform.repository.SocialPostRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/dashboard")
@CrossOrigin(origins = "*")
public class DashboardController {

    @Autowired
    private SocialPostRepository socialPostRepository;

    @Autowired
    private AdBoostRepository adBoostRepository;

    @Autowired
    private InboxMessageRepository inboxMessageRepository;

    @Autowired
    private AutopilotConfigRepository autopilotConfigRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @GetMapping("/stats")
    public DashboardResponse getDashboardStats() {
        DashboardResponse response = new DashboardResponse();
        
        response.setDrafts(socialPostRepository.countByStatus("DRAFT"));
        
        // PUBLISHED posts are the real historical posts synced into the Knowledge Base
        Long publishedCount = 0L;
        try {
            publishedCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM documents", Long.class);
        } catch (Exception e) {
            // Table might not exist yet if python script wasn't run
        }
        response.setPublished(publishedCount != null ? publishedCount : 0);
        
        response.setFailed(socialPostRepository.countByStatus("FAILED"));
        response.setScheduled(socialPostRepository.countByStatus("SCHEDULED")); 
        
        response.setActiveBoosts(adBoostRepository.countByStatus("ACTIVE"));
        response.setPendingBoosts(adBoostRepository.countByStatus("PENDING"));
        
        response.setInboxUnread(inboxMessageRepository.countByIsUnreadTrue());
        
        response.setAutoGenerated(0); // Real value is 0 until we build the auto-generation tracking
        response.setLowAccuracyDrafts(0); // Real value is 0
        
        response.setRecentPosts(socialPostRepository.findTop3ByOrderByCreatedAtDesc());
        
        List<AutopilotConfig> configs = autopilotConfigRepository.findAll();
        if (!configs.isEmpty()) {
            response.setAutopilotConfig(configs.get(0));
        }

        return response;
    }
}
