/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoStudioRouteImport } from './routes/video-studio'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PageInsightsRouteImport } from './routes/page-insights'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImageStudioRouteImport } from './routes/image-studio'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as ContentPlannerRouteImport } from './routes/content-planner'
import { Route as AutoPilotRouteImport } from './routes/auto-pilot'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'

const VideoStudioRoute = VideoStudioRouteImport.update({
  id: '/video-studio',
  path: '/video-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PageInsightsRoute = PageInsightsRouteImport.update({
  id: '/page-insights',
  path: '/page-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStudioRoute = ImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPlannerRoute = ContentPlannerRouteImport.update({
  id: '/content-planner',
  path: '/content-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoPilotRoute = AutoPilotRouteImport.update({
  id: '/auto-pilot',
  path: '/auto-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auto-pilot': typeof AutoPilotRoute
  '/content-planner': typeof ContentPlannerRoute
  '/create-post': typeof CreatePostRoute
  '/image-studio': typeof ImageStudioRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/packages': typeof PackagesRoute
  '/page-insights': typeof PageInsightsRoute
  '/queue': typeof QueueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auto-pilot': typeof AutoPilotRoute
  '/content-planner': typeof ContentPlannerRoute
  '/create-post': typeof CreatePostRoute
  '/image-studio': typeof ImageStudioRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/packages': typeof PackagesRoute
  '/page-insights': typeof PageInsightsRoute
  '/queue': typeof QueueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auto-pilot': typeof AutoPilotRoute
  '/content-planner': typeof ContentPlannerRoute
  '/create-post': typeof CreatePostRoute
  '/image-studio': typeof ImageStudioRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/packages': typeof PackagesRoute
  '/page-insights': typeof PageInsightsRoute
  '/queue': typeof QueueRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/auto-pilot'
    | '/content-planner'
    | '/create-post'
    | '/image-studio'
    | '/inbox'
    | '/knowledge-base'
    | '/packages'
    | '/page-insights'
    | '/queue'
    | '/roles'
    | '/settings'
    | '/users'
    | '/video-studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/auto-pilot'
    | '/content-planner'
    | '/create-post'
    | '/image-studio'
    | '/inbox'
    | '/knowledge-base'
    | '/packages'
    | '/page-insights'
    | '/queue'
    | '/roles'
    | '/settings'
    | '/users'
    | '/video-studio'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/auto-pilot'
    | '/content-planner'
    | '/create-post'
    | '/image-studio'
    | '/inbox'
    | '/knowledge-base'
    | '/packages'
    | '/page-insights'
    | '/queue'
    | '/roles'
    | '/settings'
    | '/users'
    | '/video-studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AutoPilotRoute: typeof AutoPilotRoute
  ContentPlannerRoute: typeof ContentPlannerRoute
  CreatePostRoute: typeof CreatePostRoute
  ImageStudioRoute: typeof ImageStudioRoute
  InboxRoute: typeof InboxRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  PackagesRoute: typeof PackagesRoute
  PageInsightsRoute: typeof PageInsightsRoute
  QueueRoute: typeof QueueRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  VideoStudioRoute: typeof VideoStudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-studio': {
      id: '/video-studio'
      path: '/video-studio'
      fullPath: '/video-studio'
      preLoaderRoute: typeof VideoStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-insights': {
      id: '/page-insights'
      path: '/page-insights'
      fullPath: '/page-insights'
      preLoaderRoute: typeof PageInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-studio': {
      id: '/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof ImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-planner': {
      id: '/content-planner'
      path: '/content-planner'
      fullPath: '/content-planner'
      preLoaderRoute: typeof ContentPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-pilot': {
      id: '/auto-pilot'
      path: '/auto-pilot'
      fullPath: '/auto-pilot'
      preLoaderRoute: typeof AutoPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AutoPilotRoute: AutoPilotRoute,
  ContentPlannerRoute: ContentPlannerRoute,
  CreatePostRoute: CreatePostRoute,
  ImageStudioRoute: ImageStudioRoute,
  InboxRoute: InboxRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  PackagesRoute: PackagesRoute,
  PageInsightsRoute: PageInsightsRoute,
  QueueRoute: QueueRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  VideoStudioRoute: VideoStudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
